name: Bug Report
description: File a bug report
labels:
  - 'status: triage'
  - 'type: bug'
body:
  - type: markdown
    attributes:
      value: >-
        NOTE: No support for compiling the project will be provided.

        For help with Galacticraft 5, please use [TeamGalacticraft/Galacticraft](https://github.com/TeamGalacticraft/Galacticraft).

        For general Galacticraft help and support visit the [Galacticraft Central Discord](http://discord.galacticraftcentral.com/)
  - type: input
    id: forge-version
    attributes:
      label: Forge Version
      description: Which version of Minecraft Forge was used?
      placeholder: 14.23.5.2768
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Galacticraft Version
      description: What version of Galacticraft are you using?
      placeholder: 4.0.2.280
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Log or Crash Report
      description: >-
        Please upload your log (latest.log or crash report) to [Github
        Gist](https://gist.github.com/)
      placeholder: 'https://gist.github.com/ghost/1a79a4d60de6718e8e5b326e338ae533'
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1. Do this
        2. Do that
        3. Crash/Bug
        ...
    validations:
      required: true
      