name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '30 1 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v7
      with:
        repo-token: ${{ github.token }}
        stale-issue-message: 'Issue has been marked stale because it has been open 7 days with no activity. Issue will be closed in 24 hours if not updated'
        close-issue-message: 'Issue closed due to no updates or activity after the previous Stale notification'
        days-before-stale: 7
        days-before-close: 1
        any-of-labels: 'Cannot Reproduce,More Information Needed'
